services:
  identity-manager:
    build: ./identity-manager
    image: src-identity-manager:latest
    volumes:
      - ./identity-manager/app:/app
      - ./volumes/identity-data:/data
    ports:
      - "8100:8000"
    environment:
      - DNS_PORT=5353
    networks:
      - telegraph-net

  client:
    build: "./client"
    networks:
      - telegraph-net

  client-alice:
    image: src-client:latest
    volumes:
      - ./client/app:/app
      - ./volumes/alice-data:/data
    ports:
      - "5001:5000"
      - "8001:8000"
    depends_on:
      - identity-manager
    environment:
      - PORT=5000
      - API_PORT=8000
      - DNS_PORT=5353
    networks:
      - telegraph-net

  client-bob:
    image: src-client:latest
    volumes:
      - ./client/app:/app
      - ./volumes/bob-data:/data
    ports:
      - "5002:5000"
      - "8002:8000"
    depends_on:
      - identity-manager
    environment:
      - PORT=5000
      - API_PORT=8000
      - DNS_PORT=5353
    networks:
      - telegraph-net

  client-ana:
    image: src-client:latest
    volumes:
      - ./client/app:/app
      - ./volumes/ana-data:/data
    ports:
      - "5003:5000"
      - "8003:8000"
    depends_on:
      - identity-manager
    environment:
      - PORT=5000
      - API_PORT=8000
      - DNS_PORT=5353
    networks:
      - telegraph-net

networks:
  telegraph-net:
    driver: bridge

