services:
  client-alice:
    image: src-client:latest
    volumes:
      - ./app:/app
      - ../volumes/alice-data:/data
    ports:
      - "5001:5000"
      - "8001:8000"
    environment:
      - PORT=5000
      - API_PORT=8000
      - UDP_PORT=5353
    networks:
      - ws

  client-bob:
    image: src-client:latest
    volumes:
      - ./app:/app
      - ../volumes/bob-data:/data
    ports:
      - "5002:5000"
      - "8002:8000"
    environment:
      - PORT=5000
      - API_PORT=8000
      - UDP_PORT=5353
    networks:
      - ws

  client-ana:
    image: src-client:latest
    volumes:
      - ./app:/app
      - ../volumes/ana-data:/data
    ports:
      - "5003:5000"
      - "8003:8000"
    environment:
      - PORT=5000
      - API_PORT=8000
      - UDP_PORT=5353
    networks:
      - ws

networks:
  ws:
    external: true